### PR TITLE
LRAC-10056 [C] channelId should be taken from the configuration first and overridden by the middleware if required.

### PR DESCRIPTION
**Pull request by kienD**
Jira Issue: [LRAC-10056](https://issues.liferay.com/browse/LRAC-10056)

### CODE REVIEW

**Review by gabrielpramos — APPROVED** [review]
LGTM

**Review by interaminense — APPROVED** [review]
LGTM

**Comment by kienD** [comment]
ci:forward

**Comment by kienD** [comment]
ci:test:sf

**Comment by kienD** [comment]
ci:forward

**Comment by kienD** [comment]
ci:forward

**Pull request closed without merging**
