### PR TITLE
LRAC-10750 [C] Add error handling to analytics.track method

### PR DESCRIPTION
**Pull request by kienD**
Jira Issue: [LRAC-10750](https://issues.liferay.com/browse/LRAC-10750)

### CODE REVIEW

**Review by interaminense — COMMENTED** [review]
Hey @kienD, is it possible to create a unit test to assert the attributeType error label?

**Comment by kienD** [comment]
@interaminense, Updated

**Review by interaminense — APPROVED** [review]
LGTM! Thank you!

**Comment by kienD** [comment]
ci:forward

**Comment by kienD** [comment]
ci:forward

**Pull request closed without merging**
