### PR TITLE
[F] LRAC-9811 Duplicate events are being sent

### PR DESCRIPTION
**Pull request by gabrielpramos**
Jira Issue [LRAC-9811](https://issues.liferay.com/browse/LRAC-9811)

### CODE REVIEW

**Review by interaminense — APPROVED** [review]
LGTM!

**Comment by kienD** [comment]
ci:forward

**Comment by kienD** [comment]
@gabrielpramos Please fix SF issues.

**Comment by gabrielpramos** [comment]
ci:test:sf

**Comment by gabrielpramos** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by kienD** [comment]
ci:test:relevant

**Comment by gabrielpramos** [comment]
ci:stop

**Comment by gabrielpramos** [comment]
ci:forward

**Comment by interaminense** [comment]
Hey @kienD, your PR is failing unit tests

**Comment by kienD** [comment]
@gabrielpramos

**Comment by gabrielpramos** [comment]
https://github.com/gabrielpramos/liferay-portal/pull/145

**Pull request closed without merging**
